# Generated by Django 4.0.5 on 2022-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Sponsor',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('chef', 'chef'), ('co-chef', 'co-chef'), ('member', 'member'), ('vp', 'vp'), ('p', 'p')], max_length=50),
        ),
    ]
