# Generated by Django 4.0.5 on 2022-06-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_role_cell_alter_role_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='cell',
        ),
        migrations.AddField(
            model_name='cell',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.member'),
        ),
    ]
