# Generated by Django 4.0.5 on 2022-06-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_role_cell_cell_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='member',
        ),
        migrations.AddField(
            model_name='role',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.cell'),
        ),
    ]
