# Generated by Django 4.0.5 on 2022-06-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_cell_members_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='chef',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chef', to='event.member'),
        ),
        migrations.AddField(
            model_name='cell',
            name='co_chef',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_chef', to='event.member'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='event.member'),
        ),
    ]
