# Generated by Django 4.0.5 on 2022-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_cell_chef_cell_co_chef_alter_cell_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlink',
            name='title',
            field=models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('linkedin', 'linkedin')], max_length=50),
        ),
    ]
