# Generated by Django 4.0.5 on 2022-06-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_member_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
