# Generated by Django 4.0.5 on 2022-06-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.IntegerField(null=True),
        ),
    ]
