# Generated by Django 4.0.5 on 2022-06-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
