# Generated by Django 4.0.5 on 2022-06-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_speaker_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
    ]
