# Generated by Django 4.0.5 on 2022-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='event.member'),
        ),
    ]
