# Generated by Django 4.0.5 on 2022-06-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_eventday_alter_event_eventday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventday'),
        ),
    ]
